// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXywSYNh0N5iRoDg1i9_LnwynO0AgVRHM',
    appId: '1:785660444362:web:1ee994c1771caf76c1fe33',
    messagingSenderId: '785660444362',
    projectId: 'fridge-to-feast',
    authDomain: 'fridge-to-feast.firebaseapp.com',
    storageBucket: 'fridge-to-feast.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ZzRdmmwnDq-jub5BBOy2N_wCDOZe0Fc',
    appId: '1:785660444362:android:6e1f7488c394f1ecc1fe33',
    messagingSenderId: '785660444362',
    projectId: 'fridge-to-feast',
    storageBucket: 'fridge-to-feast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkoLlhIuAtTbkftvLPIMRsvQ5D1cm7-1I',
    appId: '1:785660444362:ios:0c190949e5dbaf56c1fe33',
    messagingSenderId: '785660444362',
    projectId: 'fridge-to-feast',
    storageBucket: 'fridge-to-feast.appspot.com',
    iosBundleId: 'com.example.fridgeToFeast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkoLlhIuAtTbkftvLPIMRsvQ5D1cm7-1I',
    appId: '1:785660444362:ios:0c190949e5dbaf56c1fe33',
    messagingSenderId: '785660444362',
    projectId: 'fridge-to-feast',
    storageBucket: 'fridge-to-feast.appspot.com',
    iosBundleId: 'com.example.fridgeToFeast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXywSYNh0N5iRoDg1i9_LnwynO0AgVRHM',
    appId: '1:785660444362:web:7b073dbcea9e09fac1fe33',
    messagingSenderId: '785660444362',
    projectId: 'fridge-to-feast',
    authDomain: 'fridge-to-feast.firebaseapp.com',
    storageBucket: 'fridge-to-feast.appspot.com',
  );
}
